# Install script for directory: /home/erik/src/InsightApplications-3.8.0/VolviewPlugIns

# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
  SET(CMAKE_INSTALL_PREFIX "/usr/local")
ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
IF(NOT CMAKE_INSTALL_CONFIG_NAME)
  IF(BUILD_TYPE)
    STRING(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  ELSE(BUILD_TYPE)
    SET(CMAKE_INSTALL_CONFIG_NAME "")
  ENDIF(BUILD_TYPE)
  MESSAGE(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
ENDIF(NOT CMAKE_INSTALL_CONFIG_NAME)

# Set the component getting installed.
IF(NOT CMAKE_INSTALL_COMPONENT)
  IF(COMPONENT)
    MESSAGE(STATUS "Install component: \"${COMPONENT}\"")
    SET(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  ELSE(COMPONENT)
    SET(CMAKE_INSTALL_COMPONENT)
  ENDIF(COMPONENT)
ENDIF(NOT CMAKE_INSTALL_COMPONENT)

# Install shared libraries without execute permission?
IF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)
  SET(CMAKE_INSTALL_SO_NO_EXE "1")
ENDIF(NOT DEFINED CMAKE_INSTALL_SO_NO_EXE)

FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKAntiAlias.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKBinaryMedian.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKCannyEdgeDetection.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKCannySegmentationLevelSetModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKConfidenceConnected.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKConnectedThreshold.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKCurvatureAnisotropicDiffusion.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKCurvatureFlow.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKDanielssonDistanceMap.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKDeformableModelModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKFastMarching.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKFastMarchingModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKGeodesicActiveContour.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKGeodesicActiveContourModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKGradientAnisotropicDiffusion.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKGradientMagnitude.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKGradientMagnitudeRecursiveGaussian.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKImageRegistration.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKIntensityWindowing.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKIsolatedConnected.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKIsotropicFourthOrderLevelSet.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKLandmarkWarping.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKMask.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKMaskNegated.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKMedian.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKRescaleIntensityTo8Bits.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKScalarImageKMeansClassifier.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKShapeDetectionModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKSigmoid.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKSurfaceSpline.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKThresholdSegmentationLevelSet.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKVectorConfidenceConnected.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKWatershedModule.so")
FILE(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE MODULE FILES "/home/erik/src/InsightApplications-3.8.0/LandmarkInitializedMutualInformationRegistration/VolviewPlugIns/CMakeFiles/CMakeRelink.dir/libvvITKWatershedRGBModule.so")
